INSERT INTO Actor VALUE(1,"aaa","bbb", "Male", "1978-04-01", null); -- violates the constraint of primary key of Actor: ERROR 1062 (23000): Duplicate entry '1' for key 'PRIMARY'
INSERT INTO Movie VALUE(2, "test", 1997, "PG-13", "test"); -- violates the constraint of primary key of Movie: ERROR 1062 (23000): Duplicate entry '2' for key 'PRIMARY'
INSERT INTO Director VALUE(16, "first", "last", "1973-03-05", null); -- violates the constraint of primary key of Director: ERROR 1062 (23000): Duplicate entry '16' for key 'PRIMARY'
INSERT INTO MovieActor VALUE(1, 1, "test"); -- violates the constraint of foreign key aid in MovieActor: ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test`.`movieactor`, CONSTRAINT `movieactor_ibfk_1` FOREIGN KEY (`mid`) REFERENCES `Movie` (`id`))
INSERT INTO MovieActor VALUE(2, 2,"test"); -- violates the constraint of foreign key mid in MovieActor: ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test`.`movieactor`, CONSTRAINT `movieactor_ibfk_2` FOREIGN KEY (`aid`) REFERENCES `Actor` (`id`))
INSERT INTO MovieDirector VALUE(1,16); -- violates the constraint of foreign key mid in MovieDirector: ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test`.`moviedirector`, CONSTRAINT `moviedirector_ibfk_1` FOREIGN KEY (`mid`) REFERENCES `Movie` (`id`))
INSERT INTO MovieDirector VALUE(2,1); -- violates the constraint of foreign key did in MovieDirector: ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test`.`moviedirector`, CONSTRAINT `moviedirector_ibfk_2` FOREIGN KEY (`did`) REFERENCES `Director` (`id`))
INSERT INTO MovieGenre VALUE(1,"test"); -- violates the constraint of foreign key mid in MovieGenre: ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test`.`moviegenre`, CONSTRAINT `moviegenre_ibfk_1` FOREIGN KEY (`mid`) REFERENCES `Movie` (`id`))
INSERT INTO Review Value("name", "2016-10-10", 1, 1, "comment"); -- violates the constraint of foreign key mid in Review: ERROR 1452 (23000): Cannot add or update a child row: a foreign key constraint fails (`test`.`review`, CONSTRAINT `review_ibfk_1` FOREIGN KEY (`mid`) REFERENCES `Movie` (`id`))
INSERT INTO Actor VALUE(69001, "aaaa", "bbbb", "F", "1978-04-01", null); -- violates the constraint checking sex in Actor to be either "Male" or "Female";
INSERT INTO Movie VALUE(4751, "test", 1800, "PG-13", "test"); -- violates the constraint checking year in Movie to be larger than 1895;
INSERT INTO Review Value("name", "2016-10-10", 2, 10, "comment"); -- violates the constraint checking rating in Review to be larger or equal than 1 and less or equal than 5;
INSERT INTO Director(69002,"aa","bb","1975-08-14","1974-09-10") --violates the constration checking dod should be later than dob in Director